#!/bin/bash

URL=https://github.com/punchagan/ansible-system-setup.git

# Install Ansible (ansible-pull)
which ansible-pull || (sudo apt update && sudo apt install -y ansible)

ansible-pull -o -U "${URL}"
