- name: Workstation main task
  block:
  # install software
  - import_tasks: software/repositories.yml
    become: true
  - import_tasks: software/install.yml
    become: true

  # Configure system
  - import_tasks: configuration/account-service.yml
    become: true
  - import_tasks: configuration/gnome.yml
  - import_tasks: configuration/nameservers.yml
    become: true
  - import_tasks: configuration/repos.yml
  - import_tasks: configuration/dotfiles.yml
  - import_tasks: configuration/journal.yml

  rescue:
    - set_fact: task_failed=true
