- name: Workstation main task
  block:
  # install software
  - import_tasks: software/repositories.yml
  - import_tasks: software/install.yml

  # Configure system
  - import_tasks: configuration/account-service.yml
  - import_tasks: configuration/gnome.yml

  rescue:
    - set_fact: task_failed=true
