- name: system setup | install | install some basic GUI software (debian-based)
  tags: packages,gui
  package:
    name:
      - chromium-browser
      - emacs
      - emacs-gtk
      - feh
      - firefox-trunk
      - gnome-session
      - gnome-shell
      - gnome-tweaks
      - redshift
      - redshift-gtk
      - sqlitebrowser
      - terminator
      - thunderbird
      - vim
    state: latest
  when: ansible_distribution in debian_oses

- name: system setup | install | install some GUI software using CLASSIC flag (debian-based, snaps)
  community.general.snap:
    name:
      - code  # vscode
    classic: yes

- name: system setup | install | remove some pre-installed GUI software (debian-based)
  tags: packages,system,settings
  package:
    name:
      - firefox
    state: absent
  when: ansible_distribution in debian_oses

- name: system setup | install | remove some pre-installed GUI software (debian-based, snaps)
  community.general.snap:
    name: firefox
    state: absent
