- name: system setup | install | install some basic GUI software (debian-based)
  tags: packages,system,settings
  package:
    name:
      - emacs
      - firefox-trunk
      - gnome-shell
      - sqlitebrowser
      - terminator
      - thunderbird
      - vim
    state: latest
  when: ansible_distribution in debian_oses

- name: system setup | install | remove some pre-installed GUI software (debian-based)
  tags: packages,system,settings
  package:
    name:
      - firefox
    state: absent
  when: ansible_distribution in debian_oses

- name: system setup | install | remove some pre-installed GUI software (debian-based, snaps)
  community.general.snap:
    name: firefox
    state: absent
