- name: system setup | install | install some basic GUI software (debian-based)
  tags: packages,gui
  package:
    name:
      - chromium-browser
      - dconf-editor
      - emacs
      - emacs-gtk
      - feh
      - ffmpeg
      - firefox-trunk
      - gnome-session
      - gnome-shell
      - gnome-tweaks
      - redshift
      - redshift-gtk
      - sqlitebrowser
      - terminator
      - thunderbird
      - vim
      - wmctrl
      - workrave-gnome
      - xclip
      - xdotool
    state: latest
  when: ansible_distribution in debian_oses

- name: system setup | install | install some GUI software using CLASSIC flag (debian-based, snaps)
  tags: packages,gui
  community.general.snap:
    name:
      - code  # vscode
    classic: yes
  when: ansible_distribution in debian_oses

- name: system setup | install | install some TUI software (debian-based, snaps)
  tags: packages,gui
  community.general.snap:
    name:
      - git-standup
  when: ansible_distribution in debian_oses

- name: system setup | install | install prettier from beta channel
  tags: packages,gui
  community.general.snap:
    name:
      - prettier
    channel: "beta"
  when: ansible_distribution in debian_oses

- name: system setup | install | remove some pre-installed GUI software (debian-based)
  tags: packages,gui
  package:
    name:
      - firefox
    state: absent
  when: ansible_distribution in debian_oses

- name: system setup | install | remove some pre-installed GUI software (debian-based, snaps)
  tags: packages,gui
  community.general.snap:
    name: firefox
    state: absent
  when: ansible_distribution in debian_oses
