- name: user configuration | gnome | tweak all gnome settings
  include_role:
    name: petermosmans.customize-gnome
  tags: extensions,settings,dconf,fonts,files,gnome
  vars:
    gnome_user: '{{ username }}'
    gnome_dconf:
      - key: /org/gnome/desktop/background/show-desktop-icons
        value: "false"

      # Top bar

      - key: /org/gnome/desktop/interface/clock-show-seconds
        value: "false"

      - key: /org/gnome/desktop/interface/clock-show-date
        value: "true"

      - key: /org/gnome/desktop/interface/clock-show-weekday
        value: "true"

      - key: /org/gnome/desktop/calendar/show-weekdate
        value: "true"

      - key: /org/gnome/desktop/interface/show-battery-percentage
        value: "true"

      # Power settings

      - key: /org/gnome/settings-daemon/plugins/power/lid-close-suspend-with-external-monitor
        value: "false"

    gnome_extensions:
      - id: 779  # Clipboard indicator
        enable: yes

      - id: 4144  # Vertical overview
        enable: yes
  when: ansible_distribution in debian_oses

- name: Gnome shell configuration | gnome | Enable workrave extension
  tags: dotfiles
  ansible.builtin.shell: gnome-extensions enable workrave@workrave.org
  when: ansible_distribution in debian_oses
