- name: user configuration | gnome | tweak all gnome settings
  include_role:
    name: petermosmans.customize-gnome
  tags: extensions,settings,dconf,fonts,files,gnome
  vars:
    gnome_user: '{{ username }}'
    gnome_dconf:
      - key: /org/gnome/desktop/background/show-desktop-icons
        value: "false"

      # Top bar

      - key: /org/gnome/desktop/interface/clock-show-seconds
        value: "false"

      - key: /org/gnome/desktop/interface/clock-show-date
        value: "true"

      - key: /org/gnome/desktop/interface/clock-show-weekday
        value: "true"

      - key: /org/gnome/desktop/calendar/show-weekdate
        value: "true"

      - key: /org/gnome/desktop/interface/show-battery-percentage
        value: "true"

      # Power settings

      - key: /org/gnome/settings-daemon/plugins/power/lid-close-suspend-with-external-monitor
        value: "false"

      # Custom keybindings
      # NOTE: Needs Gnome shell to be restarted after this!
      - key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings
        value: "[\\'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/journal-capture/\\',\\ \\'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/journal-show/\\',\\ \\'/org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/journal-clock/\\']"

      ## Journal Capture
      - key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/journal-capture/name
        value: "\\'journal-capture\\'"

      - key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/journal-capture/binding
        value: "\\'<Shift><Super>j\\'"

      - key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/journal-capture/command
        value: "\\'/home/punchagan/bin/journal.sh\\ journal\\'"

      ## Journal Show
      - key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/journal-show/name
        value: "\\'journal-show\\'"

      - key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/journal-show/binding
        value: "\\'<Super>j\\'"

      - key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/journal-show/command
        value: "\\'/home/punchagan/bin/journal.sh\\'"

      ## Journal Clock
      - key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/journal-clock/name
        value: "\\'journal-clock\\'"

      - key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/journal-clock/binding
        value: "\\'<Super>c\\'"

      - key: /org/gnome/settings-daemon/plugins/media-keys/custom-keybindings/journal-clock/command
        value: "\\'/home/punchagan/bin/journal.sh\\ clock\\'"


    gnome_extensions:
      - id: 779  # Clipboard indicator
        enable: yes

      - id: 4144  # Vertical overview
        enable: yes
  when: ansible_distribution in debian_oses

- name: Gnome shell configuration | gnome | Enable workrave extension
  tags: dotfiles
  ansible.builtin.shell: gnome-extensions enable workrave@workrave.org
  when: ansible_distribution in debian_oses
