- name: user configuration | gnome | tweak all gnome settings
  include_role:
    name: petermosmans.customize-gnome
  tags: extensions,settings,dconf,fonts,files,gnome
  vars:
    gnome_user: '{{ username }}'
    gnome_dconf:
      - key: /org/gnome/desktop/background/show-desktop-icons
        value: "false"

      - key: /org/gnome/desktop/interface/clock-show-seconds
        value: "false"

      - key: /org/gnome/desktop/interface/clock-show-date
        value: "true"

      - key: /org/gnome/desktop/interface/clock-show-weekday
        value: "true"

      - key: /org/gnome/desktop/calendar/show-weekdate
        value: "true"

      - key: /org/gnome/desktop/interface/show-battery-percentage
        value: "true"

    gnome_extensions:
      - id: 779  # Clipboard indicator
        enable: yes

      - id: 4144  # Vertical overview
        enable: yes
