- name: life-in-plain-text configuration | journal | Clone life-in-plain-text from muse-amuse
  tags: notes,journal,git
  ansible.builtin.git:
    repo: "{{ username }}@muse-amuse.in:~/repos/.life-in-plain-text.git"
    dest: "{{ home_dir }}/.life-in-plain-text/"
    update: no
    clone: yes

- name: life-in-plain-text configuration | journal | Setup cron to backup life-in-plain-text
  tags: notes,journal,cron
  ansible.builtin.cron:
    name: "backup life-in-plain-text"
    minute: "0"
    hour: "*"
    job: "{{ home_dir }}/.life-in-plain-text/backup.sh > {{ home_dir }}/.lipt.backup.log 2>&1"

- name: life-in-plain-text configuration | journal | Setup link to run backup quickly
  tags: notes,journal
  ansible.builtin.file:
    src: "{{ home_dir }}/.life-in-plain-text/backup.sh"
    dest: "{{ home_dir }}/bin/journal-backup"
    state: link

# NOTE: See workstation/tasks/configuration/gnome.yml for keybindings setup
