- name: Code configuration | repos | Clone repos from Github (personal)
  tags: repos,git
  ansible.builtin.git:
    repo: "git@github.com:{{ git_username }}/{{ item.name }}.git"
    dest: "{{ code_dir }}/my-repos/{{ item.name }}"
    update: no
    bare: "{{ item.bare | default(false) }}"
    clone: yes
  loop:
    - {"name": "ansible-system-setup"}
    - {"name": "dotfiles", "bare": true}
    - {"name": "dot-emacs"}
    - {"name": "zulip-helpers.el"}
    - {"name": "punchagan.muse-amuse.in"}
    - {"name": "ox-gist"}

- name: Code configuration | repos | Clone bashit from Github
  tags: repos,git,bashit
  ansible.builtin.git:
    repo: "git@github.com:{{ item.remote }}"
    dest: "{{ code_dir }}/misc/{{ item.name }}"
    update: no
    clone: yes
  loop:
    - {"name": "bash-it", "remote": "Bash-it/bash-it.git"}
