- name: Code configuration | repos | Clone repos from Github (personal)
  tags: repos,git
  ignore_errors: yes
  ansible.builtin.git:
    repo: "git@github.com:{{ git_username }}/{{ item.name }}.git"
    dest: /home/{{ username }}/code/my-repos/{{ item.name }}
    update: no
    bare: "{{ item.bare | default(false) }}"
    clone: yes
  loop:
    - {"name": "ansible-system-setup"}
    - {"name": "dotfiles", "bare": true}
    - {"name": "dot-emacs"}
    - {"name": "zulip-helpers.el"}

- name: Emacs configuration | repos | Setup .emacs
  tags: repos,emacs
  ansible.builtin.file:
    src: /home/{{ username }}/code/my-repos/dot-emacs
    dest: /home/{{ username }}/.emacs.d
    state: link
