- name: Code configuration | repos | Clone repos from Github (personal)
  tags: repos,git
  ignore_errors: yes
  ansible.builtin.git:
    repo: "git@github.com:{{ git_username }}/{{ item }}.git"
    dest: /home/{{ username }}/code/my-repos/{{ item }}
    update: no
    clone: yes
  loop:
    - ansible-system-setup
    - dotfiles
    - dot-emacs
    - zulip-helpers.el


- name: Emacs configuration | repos | Setup .emacs
  tags: repos,emacs
  ansible.builtin.file:
    src: /home/{{ username }}/code/my-repos/dot-emacs
    dest: /home/{{ username }}/.emacs.d
    state: link
