- name: Code configuration | repos | Clone repos from Github (personal)
  tags: repos,git
  ansible.builtin.git:
    repo: "git@github.com:{{ git_username }}/{{ item.name }}.git"
    dest: "{{ code_dir }}/my-repos/{{ item.name }}"
    update: no
    bare: "{{ item.bare | default(false) }}"
    clone: yes
  loop:
    - {"name": "ansible-system-setup"}
    - {"name": "dotfiles", "bare": true}
    - {"name": "dot-emacs"}
    - {"name": "zulip-helpers.el"}
    - {"name": "punchagan.muse-amuse.in"}
    - {"name": "ox-gist"}

- name: Add second url to blog repo | repos | Push to muse-amuse.in
  tags: repos,git
  ansible.builtin.shell: |
    cd "{{ code_dir }}/my-repos/punchagan.muse-amuse.in"
    git remote remove origin
    git remote add origin muse-amuse.in:~/repos/muse-amuse.in.git
    git remote set-url --add --push origin muse-amuse.in:~/repos/muse-amuse.in.git
    git remote set-url --add --push origin "git@github.com:{{ git_username }}/punchagan.muse-amuse.in.git"

- name: Code configuration | repos | Clone bashit from Github
  tags: repos,git,bashit
  ansible.builtin.git:
    repo: "git@github.com:{{ item.remote }}"
    dest: "{{ code_dir }}/misc/{{ item.name }}"
    update: no
    clone: yes
  loop:
    - {"name": "bash-it", "remote": "Bash-it/bash-it.git"}
