- name: Code configuration | repos | Clone repos from Github (personal)
  tags: repos,git
  ignore_errors: yes
  ansible.builtin.git:
    repo: "git@github.com:{{ git_username }}/{{ item }}.git"
    dest: /home/{{ username }}/code/my-repos/{{ item }}
    update: no
    clone: yes
  loop:
    - ansible-system-setup
    - dot-emacs
