- name: system setup | repositories | install basic software (debian-based)
  tags: packages,terminal
  package:
    name:
      - curl
      - direnv
      - docker
      - docker-compose
      - emacs-nox
      - fasd
      - fd-find
      - fzf
      - htop
      - jq
      - make
      - mosh
      - net-tools
      - nmap
      - opam
      - p7zip-full
      - python3-venv
      - python-is-python3
      - shellcheck
      - silversearcher-ag
      - sqlite3
      - ssh
      - tmux
      - vim-nox
      - visidata
      - yamllint
    state: latest
  when: ansible_distribution in debian_oses

- name: Install hyperfine | repositories | install hyperfine (debian-based)
  tags: packages,terminal
  ansible.builtin.shell: |
    cd /tmp; wget https://github.com/sharkdp/hyperfine/releases/download/v1.13.0/hyperfine_1.13.0_amd64.deb
    dpkg -i hyperfine_1.13.0_amd64.deb
  args:
    executable: /bin/bash
