- name: system setup | repositories | install basic software (debian-based)
  tags: packages,terminal
  package:
    name:
      - curl
      - direnv
      - docker
      - docker-compose
      - emacs-nox
      - entr
      - fasd
      - fd-find
      - fzf
      - htop
      - jo
      - jq
      - linux-tools-common
      - linux-tools-generic
      - make
      - mosh
      - net-tools
      - nmap
      - opam
      - p7zip-full
      - pandoc
      - pass
      - pipx
      - python-is-python3
      - python3-venv
      - shellcheck
      - silversearcher-ag
      - sqlite3
      - ssh
      - tmux
      - vim-nox
      - visidata
      - whois
      - yamllint
    state: latest
  when: ansible_distribution in debian_oses

- name: Install hyperfine | repositories | install hyperfine (debian-based)
  tags: packages,terminal
  ansible.builtin.shell: |
    cd /tmp; wget https://github.com/sharkdp/hyperfine/releases/download/v1.13.0/hyperfine_1.13.0_amd64.deb
    dpkg -i hyperfine_1.13.0_amd64.deb
  args:
    executable: /bin/bash

- name: Install Poetry | repositories | install hyperfine (debian-based)
  tags: packages,terminal
  ansible.builtin.shell: |
    cd /tmp
    curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python -
  args:
    executable: /bin/bash
