- name: system setup | repositories | install basic software (debian-based)
  tags: packages,terminal
  package:
    name:
      - curl
      - direnv
      - docker
      - docker-compose
      - emacs-nox
      - fasd
      - fd-find
      - fzf
      - htop
      - jq
      - make
      - mosh
      - net-tools
      - nmap
      - opam
      - p7zip-full
      - python3-venv
      - python-is-python3
      - shellcheck
      - silversearcher-ag
      - sqlite3
      - ssh
      - tmux
      - vim-nox
      - visidata
    state: latest
  when: ansible_distribution in debian_oses
