- name: system setup | repositories | install basic software (debian-based)
  tags: packages,terminal
  package:
    name:
      - curl
      - docker
      - docker-compose
      - emacs-nox
      - htop
      - jq
      - make
      - mosh
      - net-tools
      - opam
      - silversearcher-ag
      - sqlite3
      - ssh
      - tmux
      - vim-nox
    state: latest
  when: ansible_distribution in debian_oses
