- name: system setup | repositories | install package management tools (debian-based)
  tags: packages,system,settings
  package:
    name:
      - aptitude
      - software-properties-common
    state: latest
  when: ansible_distribution in debian_oses

- name: system setup | repositories | add docker gpg apt key (ubuntu)
  apt_key:
    url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    state: present
  when: ansible_distribution in debian_oses

- name: system setup | repositories | add docker repository (debian-based)
  apt_repository:
    repo: deb "https://download.docker.com/linux/{{ ansible_distribution | lower }}" "{{ ansible_lsb.codename }}" stable
    state: present
    update_cache: true
  when: ansible_distribution in ["Debian", "Ubuntu"]
