- name: Base main task
  block:

  # install software
  - import_tasks: software/repositories.yml
  - import_tasks: software/install.yml

  # run configuration
  - import_tasks: configuration/ssh.yml

  rescue:
    - set_fact: task_failed=true
